language: node_js
node_js:
- '11'
script:
- npm run test:coverage
- codecov ./coverage/clover.xml
branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
deploy:
  provider: npm
  email: iceprosurface@gmail.com
  api_key:
    secure: BmoZJcdyIBtkudiKiRgIil/VfarXB6DZTNPcxIGT0phBXcdlvi/YLiLVHOrOGFiwjnj0a8OUpmzbDb4seu/RqGodR4tl5hatV/E7ooXPeeOd7R7Bz3ILTeKHmgs4zLTjLzliOSuVPocvIWAYNFKYBJGDkXBOCQ62KLV6ko3NdlHSp0y0NRYfqD/x9BApMJ3aXkqRlDD4oan6KCDl04ZZ/SYmrYObI9wpVQsT1jTyQrMjuTkRIeNO5vgIFXtWGsKeD0bYznSxwIzMqnoAWfabC2n3fsOTuaJDYNlxvSJZjMAW5Wu0veo0NeDQLTD+Exx7uBXpx9dwoOumBbApNNiegA0Hf/ug9tk6bNhKNwOsRY/liQ730pYh9iOzMaq+o12LyyrHd94zTE/SfRz+sBqOu90JdDnOxQleFvMdJ8hu51rnehidufs/tNkY1fIs1EVMPviFpkQQoG3h/5iA0L0tWy3w7zQeVxfYsxgxOGIYhmF7Xg/7oVv/EEYVm/JG7YaCF3B30dmFh02s3VaOtwdiELUcdm7ZLrysCJEC9xBfeLgCgnvtYUCQRdnw/ugwFl6cW26tpO1YXPuJ2tLiFoqOK3QtSNYONjlV5OePRyYKYVabmq4aI40rso1KMysV753bfRrA58w7aTb3FnzQG8qLbTc03Aat74EcuUUXqUD3toc=
  on:
    tags: true
    repo: iceprosurface/remote-async
