language: node_js
node_js:
- '11'
script:
- npm run test:coverage
- codecov ./coverage/clover.xml
branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
before_deploy:
- npm run build
deploy:
  provider: npm
  email: iceprosurface@gmail.com
  api_key:
    secure: qjygfU0NFK7SkY3kg6muyXvWw8BhcTYqMgQP9skXavqVf0maoybkKrv8iqsHyIgvWsMkz00iAMfMyEdm36QnS4lbFS8x9CLn/PB7TzH9yijAyMUyq60T4QPC+i5cfT+cmwAzk9Gf26GfVFx+HFU90pH6YrQnRZ+Ghc5t27XRWFaU7PSvZSYP3Gpukv8Ugk+TxQm9qWHe5TORlpVHzEoSHIWMEIcnaPd3JZ9FMVVTZuJ50IjG5YwvMawl2QoV78RdP1iJYOYvakCWg7SO6NY5JnZwwMr1/xlbX/2Rw8TVaEtoazx2fj8Kw+D7QoCFwDHt05aNlPE70kw9VZHbt1uqzFNinxiCskSXuhnRcePrekO34D7e3EEyc9Uf43KF5gQWVuCqqdi1m0rkX4QfL7fAxJer2XnScWT1crvjBIpC2rjZGYnWSD5AAq91ZWqFMG1mPn3Fw5KxBEv+xbO8HtlobKB5CSkabOxbkNZM9tmTMNGiuS6lfbka4tOyd5HsulIB0oou+o2Suobwem+7S08uq3hHJWn6q+47QJzY3aNkXcoIc1ynK7xC279hWaue891oq+RNpBEqaJw6IxjSHwh1btUll/TYJwNvWFYekofiRYQXWtj529qpER+CMjEgJlFb+xG8WkSbT0Z+occ25g8l1dscAmv3Y1HR/oHMSE7kbDc=
  on:
    tags: true
    repo: iceprosurface/remote-async
